spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: microcloud-config-eureka-client
eureka:
  instance:
    hostname: eureka-7001.com
  server:
    eviction-interval-timer-in-ms: 600000
    enable-self-preservation: true
  client:
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka
    register-with-eureka: false
    fetch-registry: false
---
server:
  port: 7001
spring:
  profiles: beta
  application:
    name: microcloud-config-eureka-client
eureka:
  instance:
    hostname: eureka-7001.com
  server:
    eviction-interval-timer-in-ms: 600000
    enable-self-preservation: true
  client:
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka
    register-with-eureka: false
    fetch-registry: false